apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
  labels:
    app: voting-app-v1
    name: postgresql
spec:
  containers:
    - name: postgresql
      image: postgresql:9.4
      ports:
        - containerPort: 5432
