apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: voting-app-v1
    name: redis-pod
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
