apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    app: voting-app-v1
    name: voting-pod
spec:
  containers:
    - name: voting-vote
      image: docker/example-voting-app-vote
      ports:
        - containerPort: 80
